export enum Tabs {
  UT = "ut",
  ST = "st"
}

export const ITEM_DIMENSION = 46;

export const ITEM_NAMES_UT = [
  "Avarice",
  "Gambler's Fate",
  "Turncoat cape",
  "Collector's Monocle",
  "Lumiaire",
  "Chaotic Scripture",
  "Vesture of Duality",
  "Divine Coronation",
  "Superior",
  "Genesis Spell",
  "Diplomatic Robe",
  "Chancellor's Cranium",
  "Enforcer",
  "Ballistic Star",
  "Centaur's Shielding",
  "Battalion Banner",
  "Divinity",
  "Oryx's Escutcheon",
  "Gladiator Guard",
  "Exalted God's Horn",
  "Helm of the Juggernaut",
  "Quiver of Thunder",
  "Thousand Shot",
  "Coral Venom Trap",
  "Trap of the Vile Spirit",
  "Tome of Holy Protection",
  "Tome of Purification",
  "Spirit Dagger",
  "Ghostly Prism",
  "Robe of the Mad Scientist",
  "Conducting Wand",
  "Scepter of Fulmination",
  "Ray Katana",
  "Midnight Star",
  "Plague Poison",
  "Resurrected Warrior's Armor",
  "Soul's Guidance",
  "Esben's Shaman Attire",
  "Esben's Wedding Ring",
  "Candy Coated Armor",
  "Leaf Dragon Hide Armor",
  "Water Dragon Silk Robe",
  "Fire Dragon Battle Armor",
  "Celestial Blade",
  "Pirate King's Cutlass",
  "Doku No Ken",
  "Leaf Bow",
  "Tablet of the King's Avatar",
  "Harlequin Armor",
  "Snake Charmer Pungi",
  "Wavecrest Concertina",
  "Pharaoh's Requiem",
  "Void Blade",
  "Murky Toxin",
  "Prism of Dire Instability",
  "Spiteful Scutum",
  "Cnidaria Rod",
  "Bottled Medusozoan",
  "Ice Crown",
  "Arcane Rapier",
  "Wand of the Fallen",
  "Kageboshi",
  "Apocalypse Feather",
  "Helm of the Swift Bunny",
  "Vitamin Buster",
  "Queen's Stinger",
  "Hivemaster Helm",
  "Yellow Beehemoth Quiver",
  "Red Beehemoth Quiver",
  "Blue Beehemoth Quiver",
  "Marble Seal",
  "Staff of Unholy Sacrifice",
  "Shield of Ogmur",
  "Bow of the Void",
  "Quiver of the Shadows",
  "Armor of Nil",
  "Sourcestone",
  "Omnipotence Ring",
  "Skull of Corrupted Souls",
  "Ritual Robe",
  "Bloodshed Ring",
  "Sword of the Colossus",
  "Breastplate of New Life",
  "Magical Lodestone",
  "Shadow Serpent Sidearm",
  "Seal of Cubic Conundra",
  "Cloak of Cubic Enigma",
  "Cloak of Bloody Surprises",
  "Dirk of Cronus",
  "Recurring Terror Spell",
  "Tome of Pain",
  "Scepter of Devastation",
  "Doom Bow",
  "Coral Bow",
  "Peacekeeper",
  "Vanguard's Visage",
  "Noble Mandolin",
  "Polarity Poison",
  "Sentinel's Sidearm",
  "Primal Arcana",
  "Valor",
  "Dusky Catalyst",
  "Warmonger",
  "Mantle of the Monarchy",
  "Vest of Abandoned Shadows",
  "Royal Guard's Cuirass",
  "The Forgotten Crown",
  "The Twilight Gemstone",
  "Bracer of the Guardian",
  "Ring of the Sphinx",
  "Ring of the Nile",
  "Ring of the Pyramid",
  "Enchanted Ice Shard",
  "Ring of the Northern Light",
  "Frimarra"
];
