export enum TAB {
  UT = "ut",
  ST = "st",
  BP = "bp"
}

export enum ITEM_TYPE {
  WEAPON = 1,
  ABILITY,
  ARMOR,
  RING
}

export enum BP_QUALITY {
  BASIC = 1,
  GREATER,
  SUPERIOR,
  PARAMOUNT,
  EXALTED,
  FESTIVE,
  INCUBATION
}

export enum SOURCE {
  PIRATE_CAVE = 1,
  FOREST_MAZE,
  SPIDER_DEN,
  FORBIDDEN_JUNGLE,
  THE_HIVE,
  CANDYLAND_HUNTING_GROUNDS,
  ANCIENT_RUINS,
  MAGIC_WOODS,
  SNAKE_PIT,
  SPRITE_WORLD,
  CAVE_OF_A_THOUSAND_TREASURES,
  UNDEAD_LAIR,
  MANOR_OF_THE_IMMORTALS,
  PUPPET_MASTERS_THEATRE,
  TOXIC_SEWERS,
  CURSED_LIBRARY,
  MAD_LAB,
  ABYSS_OF_DEMONS,
  HAUNTED_CEMETERY,
  THE_MACHINE,
  THE_INNER_WORKINGS,
  THE_CRAWLING_DEPTHS,
  PARASITE_CHAMBERS,
  WOODLAND_LABYRINTH,
  DEADWATER_DOCKS,
  BEACHZONE,
  DAVY_JONES_LOCKER,
  ICE_CAVE,
  MOUNTAIN_TEMPLE,
  LAIR_OF_DRACONIS,
  OCEAN_TRENCH,
  TOMB_OF_THE_ANCIENTS,
  THE_THIRD_DIMENSION,
  THE_NEST,
  FUNGAL_CAVERN,
  CRYSTAL_CAVERN,
  LOST_HALLS,
  CULTIST_HIDEOUT,
  THE_VOID,
  THE_SHATTERS,
  ALIENS,
  ORYXS_CHAMBER,
  WINE_CELLAR,
  COURT_OF_ORYX,
  ORYXS_SANCTUARY,
  PUPPET_MASTERS_ENCORE,
  LAIR_OF_SHAITAN,
  CNIDARIAN_REEF,
  SECLUDED_THICKET,
  HIGH_TECH_TERROR,
  RAINBOW_ROAD,
  SANTAS_WORKSHOP,
  ICE_TOMB,
  BATTLE_FOR_THE_NEXUS,
  BELLADONNAS_GARDEN,
  MAD_GOD_MAYHEM,
  HIDDEN_INTERREGNUM,
  EVENT,
  REALM,
  FORGE,
  ORYX_CASTLE,
  HEROIC_UNDEAD_LAIR,
  TRADING,
  REALM_EVENT_BOSS,
  WETLANDS,
  BLUEPRINT_ROTATION,
  BAZAAR,
  GODLANDS_DUNGEONS
}

export const ITEM_DIMENSION = 46;

export const BP_QUALITY_POS = {
  [BP_QUALITY.BASIC]: {
    x: -184,
    y: -92
  },
  [BP_QUALITY.GREATER]: {
    x: -138,
    y: -92
  },
  [BP_QUALITY.SUPERIOR]: {
    x: -92,
    y: -92
  },
  [BP_QUALITY.PARAMOUNT]: {
    x: -46,
    y: -92
  },
  [BP_QUALITY.EXALTED]: {
    x: 0,
    y: -92
  },
  [BP_QUALITY.FESTIVE]: {
    x: -230,
    y: -92
  },
  [BP_QUALITY.INCUBATION]: {
    x: -276,
    y: -92
  }
};

export const ITEM_TYPE_NAMES = {
  [ITEM_TYPE.ABILITY]: "Ability",
  [ITEM_TYPE.ARMOR]: "Armor",
  [ITEM_TYPE.RING]: "Ring",
  [ITEM_TYPE.WEAPON]: "Weapon"
};

export const SOURCE_NAMES = {
  [SOURCE.ABYSS_OF_DEMONS]: "Abyss of Demons",
  [SOURCE.ALIENS]: "Aliens",
  [SOURCE.ANCIENT_RUINS]: "Ancient Ruins",
  [SOURCE.BATTLE_FOR_THE_NEXUS]: "Battle for the Nexus",
  [SOURCE.BEACHZONE]: "Beachzone",
  [SOURCE.BELLADONNAS_GARDEN]: "Belladonna's Garden",
  [SOURCE.CANDYLAND_HUNTING_GROUNDS]: "Candyland Hunting Grounds",
  [SOURCE.CAVE_OF_A_THOUSAND_TREASURES]: "Cave of a Thousand Treasures",
  [SOURCE.CNIDARIAN_REEF]: "Cnidarian Reef",
  [SOURCE.COURT_OF_ORYX]: "Court of Oryx",
  [SOURCE.CRYSTAL_CAVERN]: "Crystal Cavern",
  [SOURCE.CULTIST_HIDEOUT]: "Cultist Hideout",
  [SOURCE.CURSED_LIBRARY]: "Cursed Library",
  [SOURCE.DAVY_JONES_LOCKER]: "Davy Jones' Locker",
  [SOURCE.DEADWATER_DOCKS]: "Deadwater Docks",
  [SOURCE.EVENT]: "Event",
  [SOURCE.FORBIDDEN_JUNGLE]: "Forbidden Jungle",
  [SOURCE.FOREST_MAZE]: "Forest Maze",
  [SOURCE.FORGE]: "Forge",
  [SOURCE.FUNGAL_CAVERN]: "Fungal Cavern",
  [SOURCE.HAUNTED_CEMETERY]: "Haunted Cemetery",
  [SOURCE.HEROIC_UNDEAD_LAIR]: "Heroic Undead Lair",
  [SOURCE.HIDDEN_INTERREGNUM]: "Hidden Interregnum",
  [SOURCE.HIGH_TECH_TERROR]: "High Tech Terror",
  [SOURCE.ICE_CAVE]: "Ice cave",
  [SOURCE.ICE_TOMB]: "Ice Tomb",
  [SOURCE.LAIR_OF_DRACONIS]: "Lair of Draconis",
  [SOURCE.LAIR_OF_SHAITAN]: "Lair of Shaitan",
  [SOURCE.LOST_HALLS]: "Lost Halls",
  [SOURCE.MAD_GOD_MAYHEM]: "Mad God Mayhem",
  [SOURCE.MAD_LAB]: "Mad Lab",
  [SOURCE.MAGIC_WOODS]: "Magic Woods",
  [SOURCE.MANOR_OF_THE_IMMORTALS]: "Manor of the Immortals",
  [SOURCE.MOUNTAIN_TEMPLE]: "Mountain Temple",
  [SOURCE.OCEAN_TRENCH]: "Ocean Trench",
  [SOURCE.ORYXS_CHAMBER]: "Oryx's Chamber",
  [SOURCE.ORYXS_SANCTUARY]: "Oryx's Sanctuary",
  [SOURCE.ORYX_CASTLE]: "Oryx's Castle",
  [SOURCE.PARASITE_CHAMBERS]: "Parasite Chambers",
  [SOURCE.PIRATE_CAVE]: "Pirate Cave",
  [SOURCE.PUPPET_MASTERS_ENCORE]: "Pupper Master's Encore",
  [SOURCE.PUPPET_MASTERS_THEATRE]: "Pupper Master's Theatre",
  [SOURCE.RAINBOW_ROAD]: "Rainbow Road",
  [SOURCE.REALM]: "Realm",
  [SOURCE.SANTAS_WORKSHOP]: "Santa's Workshop",
  [SOURCE.SECLUDED_THICKET]: "Secluded Thicket",
  [SOURCE.SNAKE_PIT]: "Snake Pit",
  [SOURCE.SPIDER_DEN]: "Spider Den",
  [SOURCE.SPRITE_WORLD]: "Sprite World",
  [SOURCE.THE_CRAWLING_DEPTHS]: "The Crawling Depths",
  [SOURCE.THE_HIVE]: "The Hive",
  [SOURCE.THE_INNER_WORKINGS]: "The Inner Workings",
  [SOURCE.THE_MACHINE]: "The Machine",
  [SOURCE.THE_NEST]: "The Nest",
  [SOURCE.THE_SHATTERS]: "The Shatters",
  [SOURCE.THE_THIRD_DIMENSION]: "The Third Dimension",
  [SOURCE.THE_VOID]: "The Void",
  [SOURCE.TOMB_OF_THE_ANCIENTS]: "Tomb of the Ancients",
  [SOURCE.TOXIC_SEWERS]: "Toxic Sewers",
  [SOURCE.TRADING]: "Trading",
  [SOURCE.UNDEAD_LAIR]: "Undead Lair",
  [SOURCE.WINE_CELLAR]: "Wine Cellar",
  [SOURCE.WOODLAND_LABYRINTH]: "Woodland Labyrinth",
  [SOURCE.REALM_EVENT_BOSS]: "Realm Event Boss",
  [SOURCE.WETLANDS]: "Wetlands",
  [SOURCE.BLUEPRINT_ROTATION]: "Blueprint Rotation",
  [SOURCE.BAZAAR]: "Bazaar",
  [SOURCE.GODLANDS_DUNGEONS]: "Godlands Dungeons"
};
