export enum Tabs {
  UT = "ut",
  ST = "st"
}

export const ITEM_DIMENSION = 46;

export const ITEM_NAMES_UT = [
  "Avarice",
  "Gambler's Fate",
  "Turncoat cape",
  "Collector's Monocle",
  "Lumiaire",
  "Chaotic Scripture",
  "Vesture of Duality",
  "Divine Coronation",
  "Superior",
  "Genesis Spell",
  "Diplomatic Robe",
  "Chancellor's Cranium",
  "Enforcer",
  "Ballistic Star",
  "Centaur's Shielding",
  "Battalion Banner",
  "Divinity",
  "Oryx's Escutcheon",
  "Gladiator Guard",
  "Exalted God's Horn",
  "Helm of the Juggernaut",
  "Quiver of Thunder",
  "Thousand Shot",
  "Coral Venom Trap",
  "Trap of the Vile Spirit",
  "Tome of Holy Protection",
  "Tome of Purification",
  "Spirit Dagger",
  "Ghostly Prism",
  "Robe of the Mad Scientist",
  "Conducting Wand",
  "Scepter of Fulmination",
  "Ray Katana",
  "Midnight Star",
  "Plague Poison",
  "Resurrected Warrior's Armor",
  "Soul's Guidance",
  "Esben's Shaman Attire",
  "Esben's Wedding Ring",
  "Candy Coated Armor",
  "Leaf Dragon Hide Armor",
  "Water Dragon Silk Robe",
  "Fire Dragon Battle Armor",
  "Celestial Blade",
  "Pirate King's Cutlass",
  "Doku No Ken",
  "Leaf Bow",
  "Tablet of the King's Avatar",
  "Harlequin Armor",
  "Snake Charmer Pungi",
  "Wavecrest Concertina",
  "Pharaoh's Requiem",
  "Void Blade",
  "Murky Toxin",
  "Prism of Dire Instability",
  "Spiteful Scutum",
  "Cnidaria Rod",
  "Bottled Medusozoan",
  "Ice Crown",
  "Arcane Rapier",
  "Wand of the Fallen",
  "Kageboshi",
  "Apocalypse Feather",
  "Helm of the Swift Bunny",
  "Vitamin Buster",
  "Queen's Stinger",
  "Hivemaster Helm",
  "Yellow Beehemoth Quiver",
  "Red Beehemoth Quiver",
  "Blue Beehemoth Quiver",
  "Marble Seal",
  "Staff of Unholy Sacrifice",
  "Shield of Ogmur",
  "Bow of the Void",
  "Quiver of the Shadows",
  "Armor of Nil",
  "Sourcestone",
  "Omnipotence Ring",
  "Skull of Corrupted Souls",
  "Ritual Robe",
  "Bloodshed Ring",
  "Sword of the Colossus",
  "Breastplate of New Life",
  "Magical Lodestone",
  "Shadow Serpent Sidearm",
  "Seal of Cubic Conundra",
  "Cloak of Cubic Enigma",
  "Cloak of Bloody Surprises",
  "Dirk of Cronus",
  "Recurring Terror Spell",
  "Tome of Pain",
  "Scepter of Devastation",
  "Doom Bow",
  "Coral Bow",
  "Peacekeeper",
  "Vanguard's Visage",
  "Noble Mandolin",
  "Polarity Poison",
  "Sentinel's Sidearm",
  "Primal Arcana",
  "Valor",
  "Dusky Catalyst",
  "Warmonger",
  "Mantle of the Monarchy",
  "Vest of Abandoned Shadows",
  "Royal Guard's Cuirass",
  "The Forgotten Crown",
  "The Twilight Gemstone",
  "Bracer of the Guardian",
  "Ring of the Sphinx",
  "Ring of the Nile",
  "Ring of the Pyramid",
  "Enchanted Ice Shard",
  "Ring of the Northern Light",
  "Frimarra",
  "Volcanic Sheath",
  "Kaiken",
  "Labyrinth Dweller's Sheath",
  "Quartermaster Scabbard",
  "Irradiance Sheath",
  "Paper Machete",
  "Seal of Blasphemous Prayer",
  "Cloak of the Planewalker",
  "Skull of Endless Torment",
  "Staff of Extreme Prejudice",
  "Barnacle Basher",
  "Corruption Cutter",
  "Scholar's Seal",
  "K.I.D.D. Force",
  "MMace MMurderer",
  "Mister Mango",
  "Butter Bow",
  "Caduceus of Current Craziness",
  "Blade of Ages",
  "Mirror Cloak",
  "Archerang",
  "Spelling Spell",
  "Tome of Moral Support",
  "Challenger Helm",
  "Shield of Pogmur",
  "Lightning in a Bottle",
  "Epiphany Skull",
  "Helium Trap",
  "Karma Orb",
  "Fool's Prism",
  "Honey Scepter Supreme",
  "Unshuriken",
  "NSFWakizashi",
  "Gem of Tenderness",
  "Gem of Adoration",
  "Soulful Affection",
  "Beekeeper's Flamethrower",
  "Crystal Wand",
  "Wand of the Bulwark",
  "Crystal Sword",
  "Demon Blade",
  "Mace of the Celestial Forest",
  "Mace of the Depths",
  "Hivemind Mace",
  "Crystal Mace",
  "Recursion Mace",
  "Orb of Aether",
  "Silex's Hammer",
  "Jade Storm",
  "Cloak of the Mad God",
  "Shield of Flowing Clarity",
  "Sealed Crystal Skull",
  "Penetrating Blast Spell",
  "Tome of the Mushroom Tribes",
  "Sporous Spray Spell",
  "Fungal Breastplate",
  "Echoes Prism",
  "Crystal Shield",
  "Crystallised Fang's Venom",
  "Crystallised Mist",
  "Cave Dweller Trap",
  "Cloak of Refraction",
  "Fractured Gemstone Wakizashi",
  "Star of Enlightenment",
  "Burial Blades",
  "Fractal Blades",
  "Perennial Cranium",
  "Clover Bow",
  "Sword of the Rainbow's End",
  "Katana of Good Fortune",
  "Clover Star",
  "Evergreen Dagger",
  "Sleigh Bell Staff",
  "Brass Chamberstick",
  "Cheerful Chipper",
  "Candy Katana",
  "Garland Bow"
];
